# -*- coding: utf-8 -*-
"""linear_regression_from_scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rashmibenni292-benni/linear-regression-from-scratch/blob/main/notebooks/linear_regression_from_scratch.ipynb
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.datasets import fetch_california_housing
import pandas as pd

housing = fetch_california_housing(as_frame=True)
data = housing.frame

data.rename(columns={"MedHouseVal": "price"}, inplace=True)

data.head()

data.info()

data.to_csv("housing.csv", index=False)

from google.colab import files
files.download("housing.csv")

data.describe()

data.isnull().sum()

sns.histplot(data["price"], kde=True)
plt.title("Price Distribution")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(data.corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation")
plt.show()

X = data.drop("price", axis=1)
y = data["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

class LinearRegressionScratch:
    def __init__(self, lr=0.01, epochs=2000):
        self.lr = lr
        self.epochs = epochs

    def fit(self, X, y):
        self.m, self.n = X.shape
        self.W = np.zeros(self.n)
        self.b = 0

        for _ in range(self.epochs):
            y_pred = np.dot(X, self.W) + self.b
            dw = (1/self.m) * np.dot(X.T, (y_pred - y))
            db = (1/self.m) * np.sum(y_pred - y)

            self.W -= self.lr * dw
            self.b -= self.lr * db

    def predict(self, X):
        return np.dot(X, self.W) + self.b

scratch_model = LinearRegressionScratch()
scratch_model.fit(X_train_scaled, y_train)

y_pred_scratch = scratch_model.predict(X_test_scaled)

sk_model = LinearRegression()
sk_model.fit(X_train_scaled, y_train)

y_pred_sk = sk_model.predict(X_test_scaled)

def evaluate(y_true, y_pred):
    print("MAE:", mean_absolute_error(y_true, y_pred))
    print("MSE:", mean_squared_error(y_true, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_true, y_pred)))
    print("R2:", r2_score(y_true, y_pred))

evaluate(y_test, y_pred_sk)

residuals = y_test - y_pred_sk

sns.scatterplot(x=y_pred_sk, y=residuals)
plt.axhline(0, color='red')
plt.title("Residual Plot")
plt.show()

